let employes=[{"id":1,"first_name":"Roderich","gender":"Male","country":"Chile"},
{"id":2,"first_name":"Veronique","gender":"Female","country":"Ukraine"},
{"id":3,"first_name":"Caroljean","gender":"Female","country":"China"},
{"id":4,"first_name":"Caterina","gender":"Female","country":"Comoros"},
{"id":5,"first_name":"Philippa","gender":"Female","country":"Philippines"},
{"id":6,"first_name":"Jerome","gender":"Male","country":"Indonesia"},
{"id":7,"first_name":"Griff","gender":"Male","country":"Indonesia"},
{"id":8,"first_name":"George","gender":"Non-binary","country":"China"},
{"id":9,"first_name":"Johnny","gender":"Male","country":"China"},
{"id":10,"first_name":"Pincus","gender":"Male","country":"China"},
{"id":11,"first_name":"Marne","gender":"Female","country":"China"},
{"id":12,"first_name":"Jen","gender":"Female","country":"Philippines"},
{"id":13,"first_name":"Borg","gender":"Male","country":"Philippines"},
{"id":14,"first_name":"West","gender":"Male","country":"Brazil"},
{"id":15,"first_name":"Berny","gender":"Bigender","country":"Indonesia"},
{"id":16,"first_name":"Pren","gender":"Male","country":"Benin"},
{"id":17,"first_name":"Duane","gender":"Male","country":"Colombia"},
{"id":18,"first_name":"Pooh","gender":"Female","country":"United States"},
{"id":19,"first_name":"Hubie","gender":"Male","country":"Guatemala"},
{"id":20,"first_name":"Prudy","gender":"Female","country":"Greece"},
{"id":21,"first_name":"Daveen","gender":"Female","country":"Greece"},
{"id":22,"first_name":"Vita","gender":"Female","country":"Sweden"},
{"id":23,"first_name":"Rice","gender":"Male","country":"Indonesia"},
{"id":24,"first_name":"Dominica","gender":"Female","country":"Libya"},
{"id":25,"first_name":"Cecile","gender":"Female","country":"Portugal"},
{"id":26,"first_name":"Ezekiel","gender":"Male","country":"Kenya"},
{"id":27,"first_name":"Peter","gender":"Male","country":"Russia"},
{"id":28,"first_name":"Ethelbert","gender":"Male","country":"Poland"},
{"id":29,"first_name":"Burtie","gender":"Male","country":"Indonesia"},
{"id":30,"first_name":"Arman","gender":"Male","country":"United Kingdom"},
{"id":31,"first_name":"Antony","gender":"Male","country":"Mexico"},
{"id":32,"first_name":"Ines","gender":"Non-binary","country":"Indonesia"},
{"id":33,"first_name":"Billi","gender":"Female","country":"Argentina"},
{"id":34,"first_name":"Prince","gender":"Male","country":"China"},
{"id":35,"first_name":"Clifford","gender":"Male","country":"China"},
{"id":36,"first_name":"Betsey","gender":"Female","country":"Russia"},
{"id":37,"first_name":"Brockie","gender":"Male","country":"China"},
{"id":38,"first_name":"Norma","gender":"Female","country":"Ukraine"},
{"id":39,"first_name":"Goran","gender":"Male","country":"Greece"},
{"id":40,"first_name":"Joseito","gender":"Male","country":"China"},
{"id":41,"first_name":"Maynord","gender":"Agender","country":"Brazil"},
{"id":42,"first_name":"Adrea","gender":"Female","country":"Mongolia"},
{"id":43,"first_name":"Ophelie","gender":"Female","country":"Senegal"},
{"id":44,"first_name":"Dianemarie","gender":"Female","country":"Democratic Republic of the Congo"},
{"id":45,"first_name":"Amity","gender":"Female","country":"China"},
{"id":46,"first_name":"Wood","gender":"Male","country":"Portugal"},
{"id":47,"first_name":"Reidar","gender":"Male","country":"Russia"},
{"id":48,"first_name":"Merrie","gender":"Female","country":"China"},
{"id":49,"first_name":"Christal","gender":"Female","country":"Portugal"},
{"id":50,"first_name":"Elva","gender":"Female","country":"Mauritania"},
{"id":51,"first_name":"Minette","gender":"Female","country":"Philippines"},
{"id":52,"first_name":"Cindee","gender":"Female","country":"Mexico"},
{"id":53,"first_name":"Darbie","gender":"Female","country":"Slovenia"},
{"id":54,"first_name":"Gae","gender":"Female","country":"China"},
{"id":55,"first_name":"Tiphanie","gender":"Female","country":"China"},
{"id":56,"first_name":"Welch","gender":"Male","country":"Kazakhstan"},
{"id":57,"first_name":"Clayson","gender":"Bigender","country":"United States"},
{"id":58,"first_name":"Hewie","gender":"Male","country":"Greenland"},
{"id":59,"first_name":"Morey","gender":"Male","country":"Kazakhstan"},
{"id":60,"first_name":"Maggie","gender":"Female","country":"Ireland"},
{"id":61,"first_name":"Tally","gender":"Male","country":"Czech Republic"},
{"id":62,"first_name":"Daisie","gender":"Female","country":"Indonesia"},
{"id":63,"first_name":"Marcia","gender":"Polygender","country":"Cuba"},
{"id":64,"first_name":"Marina","gender":"Female","country":"Nigeria"},
{"id":65,"first_name":"Efren","gender":"Male","country":"China"},
{"id":66,"first_name":"Gussie","gender":"Female","country":"Cameroon"},
{"id":67,"first_name":"Michel","gender":"Male","country":"Russia"},
{"id":68,"first_name":"Ainsley","gender":"Female","country":"China"},
{"id":69,"first_name":"Kally","gender":"Female","country":"Russia"},
{"id":70,"first_name":"Duky","gender":"Male","country":"United States"},
{"id":71,"first_name":"Bart","gender":"Male","country":"Poland"},
{"id":72,"first_name":"Lucila","gender":"Female","country":"China"},
{"id":73,"first_name":"Renado","gender":"Male","country":"Indonesia"},
{"id":74,"first_name":"Sasha","gender":"Male","country":"Peru"},
{"id":75,"first_name":"Emmery","gender":"Male","country":"Japan"},
{"id":76,"first_name":"Britni","gender":"Genderfluid","country":"Ethiopia"},
{"id":77,"first_name":"Stace","gender":"Female","country":"Russia"},
{"id":78,"first_name":"Mortie","gender":"Male","country":"Algeria"},
{"id":79,"first_name":"Zach","gender":"Male","country":"Costa Rica"},
{"id":80,"first_name":"Pauly","gender":"Male","country":"China"},
{"id":81,"first_name":"Ingram","gender":"Male","country":"China"},
{"id":82,"first_name":"Vikky","gender":"Female","country":"Colombia"},
{"id":83,"first_name":"Kip","gender":"Male","country":"Philippines"},
{"id":84,"first_name":"Euphemia","gender":"Female","country":"Greece"},
{"id":85,"first_name":"Anne-marie","gender":"Female","country":"Russia"},
{"id":86,"first_name":"Florinda","gender":"Female","country":"Thailand"},
{"id":87,"first_name":"Adelice","gender":"Female","country":"Dominican Republic"},
{"id":88,"first_name":"Bud","gender":"Male","country":"Indonesia"},
{"id":89,"first_name":"Ogdon","gender":"Male","country":"Philippines"},
{"id":90,"first_name":"Adina","gender":"Female","country":"China"},
{"id":91,"first_name":"Earl","gender":"Male","country":"Ireland"},
{"id":92,"first_name":"Maribeth","gender":"Female","country":"Philippines"},
{"id":93,"first_name":"Barby","gender":"Female","country":"Greece"},
{"id":94,"first_name":"Jeannine","gender":"Female","country":"Indonesia"},
{"id":95,"first_name":"Judie","gender":"Female","country":"Portugal"},
{"id":96,"first_name":"Dorree","gender":"Polygender","country":"Russia"},
{"id":97,"first_name":"Gerhardt","gender":"Male","country":"Panama"},
{"id":98,"first_name":"Ellary","gender":"Male","country":"Madagascar"},
{"id":99,"first_name":"Gusella","gender":"Agender","country":"Philippines"},
{"id":100,"first_name":"Sargent","gender":"Male","country":"Netherlands"},
{"id":101,"first_name":"Hamel","gender":"Male","country":"Tanzania"},
{"id":102,"first_name":"Ash","gender":"Male","country":"Nigeria"}]
let femals_count=0
for (let i=0;i<=employes.length-1;i++){
   if(employes[i].gender==="Female"&& employes[i].country==="China")
    femals_count++;
}
console.log("femals_count: " + femals_count);